version: "3"
services:
  app:
    build: .
    container_name: spring-container
    ports:
      - "80:8080"
    tty: true
  db:
    image: mysql:5.7
    container_name: mysql-container
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my/cnf
    environment:
      MYSQL_DATABASE: facebook
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword